# Generated by Django 4.1.5 on 2023-02-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeing date')),
                ('meal', models.CharField(choices=[('R', 'ReefRoids'), ('A', 'Brightwell Ab+'), ('B', 'Benepets')], default='R', max_length=1)),
                ('coral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coral')),
            ],
        ),
        migrations.AddField(
            model_name='coral',
            name='food',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
