# Generated by Django 4.1.5 on 2023-02-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coral',
            name='food',
        ),
    ]
