# Generated by Django 4.1.5 on 2023-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_coral_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Meds',
        ),
        migrations.AddField(
            model_name='coral',
            name='meds',
            field=models.ManyToManyField(to='main_app.meds'),
        ),
    ]
