# Generated by Django 4.1.5 on 2023-02-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_coral_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coral',
            name='user',
        ),
    ]
